springdoc:
  swagger-ui:
    tagsSorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
ipinfo:
  lite-url: https://api.ipinfo.io
  token: ec2e0de10eeaea
  geo-url: https://ipinfo.io